name: prelude
version: 0.0.0
homepage: https://github.com/morloc-lib/prelude
synopsis: A minimal prelude
description: Includes only the Packable typeclass required for internal serialization
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-lib/prelude
bug-reports: https://github.com/morloc-lib/prelude
